## Constants

In [228]:
DATA_PATH = 'C:/Users/Thrax/Stackover_survey/Survey_analysis/data/raw/survey_results_public.csv'
EXPORT_PATH = 'C:/Users/Thrax/Stackover_survey/Survey_analysis/data/processed/preprocessed_df.pkl'


REPLACE_DICT = {
    'YearsCodePro': {'Less than 1 year': 0, 'More than 50 years': 51}, 
    'YearsCode':    {'Less than 1 year': 0, 'More than 50 years': 51}, 
    'Age1stCode':   {'Older than 85':86,    'Younger than 5 years':4}}

## Import tools

In [56]:
import pandas as pd
from pandas.api.types import is_string_dtype
import numpy as np
import pickle

## Functions

In [206]:
def split_answers(pd_series, delimiter):
    
    # Sub-function that check if the series splitable
    def is_splitable(pd_series, delimiter):
        return pd_series.str.contains(delimiter)
    
    # Sub-function that split single answer
    def split_answer(pd_series, delimiter):
        return pd_series.str.split(delimiter)
    
    # Check if there multiple answers in the series, if not return original
    splitable_values = is_splitable(pd_series, delimiter)
    
    # use any() method to check if there any false in the series
    if not splitable_values.any():
        return pd_series # if there is no multiple answers, return the original
   
    # What if there multiple answers? aka: 'else'
    
    splited_series = split_answer(pd_series, delimiter)
    
    #Replace the NaNs to avoid any error
    null_mask = splited_series.isnull()
    splited_series.loc[null_mask] = splited_series.loc[null_mask].apply(lambda x: [])
    
    return splited_series

In [197]:
raw_df = pd.read_csv(DATA_PATH) # Make a copy from the original data
df_copy = raw_df.copy()

## Values replacment

In [198]:
for col, replacment in REPLACE_DICT.items():
    df_copy[col] = df_copy[col].replace(replacment).astype(np.float64)

## Split multiple answers

In [207]:
categorical_cols = df_copy.select_dtypes(include='object').columns.tolist()

for col in categorical_cols:
    df_copy[col] = split_answers(df_copy[col], ';')

In [208]:
df_copy.sample(5).head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
9182,9214,I am a developer by profession,Yes,23.0,10.0,Yearly,35000.0,37834.0,Germany,European Euro,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",[],[jQuery],Just as welcome now as I felt last year,43.0,13.0,5.0
35653,35812,I am a developer by profession,No,NaN,12.0,NaN,NaN,NaN,United States,United States dollar,...,NaN,NaN,NaN,"Information systems, information technology, o...",[],[],NaN,NaN,27.0,14.0
61730,62992,"I used to be a developer by profession, but no...",No,NaN,NaN,NaN,NaN,NaN,Canada,NaN,...,NaN,NaN,NaN,NaN,"[Angular, React.js]","[ASP.NET, Drupal, jQuery]",NaN,NaN,NaN,NaN
35822,35994,"I am not primarily a developer, but I write co...",Yes,NaN,17.0,Yearly,167000.0,167000.0,United States,United States dollar,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",[],[],NaN,35.0,12.0,3.0
44784,45706,I am a developer by profession,Yes,22.0,17.0,Monthly,NaN,NaN,Brazil,Brazilian real,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...","[Angular.js, Django, Vue.js]","[Angular, ASP.NET, jQuery]",Just as welcome now as I felt last year,40.0,5.0,3.0

## Export the data

In [229]:
df_copy.to_pickle(EXPORT_PATH)